import Image from "next/image";
import React from "react";

export const metadata = {
  title: "Sarthak",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      {/* Header Section */}
      <header className="text-center py-20">
        <h1 className="text-9xl leading-relaxed "> About Me </h1>
      </header>

      {/* Image Section */}
      <section className="flex justify-center py-10">
        <div className="w-42 h-48 rounded-full overflow-hidden border-4 border-gray-300">
          <Image
            src="/photo.jpg"
            alt="Profile Picture"
            width={182}
            height={152}
            className="object-cover"
          />
        </div>
      </section>

      {/* About Me Section */}
      <section id="about-me" className="py-10 px-5">
        <h2 className="text-3xl font-bold mb-4 ">About Me</h2>
        <p className="text-lg">
          I am a student studying in SRM Institute of Science and Technology, Chennai. I am a passionate developer with a love for creating web applications. I have experience in Python, JavaScript, CSS, HTML and C++. I enjoy working on projects that challenge me and help me grow as a developer. I am always eager to learn new technologies and improve my skills. In my free time, I enjoy playing video games and exploring new places. I am also an avid reader and love to read books on various topics, including Fiction and Romance.
        </p>
      </section>
    </div>
  );
}
