import Image from "next/image";
import React from "react";

export const metadata = {
  title: "Sarthak",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      {/* Header Section */}
      <header className="text-center py-20">
        <h1 className="text-9xl leading-relaxed ">
          Sarthak Srivastava
        </h1>
        <h2 className="text-5xl"><span className="inline-block transition-transform duration-500 ease-in-out transform hover:scale-115">Programmer</span><span className="inline-block px-7">|</span><span className="inline-block transition-transform duration-500 ease-in-out transform hover:scale-115">Student</span></h2>
      </header>

      {/* About Me Section */}
      <section id="about-me" className="py-10 px-5">
        <h2 className="text-3xl font-bold mb-4 ">About Me</h2>
        <p className="text-lg">
          I am a passionate developer with a love for creating web applications.
        </p>
      </section>

      {/* Projects Section */}
      <section id="projects" className="py-10 px-5">
        <h2 className="text-3xl font-bold mb-4">Projects</h2>
        <ul>
          <li className="mb-2">Project 1 - Space Invaders Game developed using Pygame</li>
          <li className="mb-2">Project 2 - Flappy Bird Game developed using Pygame</li>
        </ul>
      </section>

      {/* Contact Section */}
      <section id="contact" className="py-10 px-5">
        <h2 className="text-3xl font-bold mb-4 ">Contact</h2>
        <p className="text-lg">Feel free to reach out to me at: <a href="mailto:sarthak.srivastav186@gmail.com" className="text-blue-500 hover:underline hover:text-white;">sarthak.srivastav186@gmail.com</a></p>
      </section>
    </div>
  );
}
